spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?useUnicode=true&amp;characterEncoding=utf-8
env:
  test
server:
  port: 8082
