spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/activiti6unit?useUnicode=true&amp;characterEncoding=utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
server:
  port: 8082
